name: Publish to personal AUR
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies and build package
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git base-devel sudo go
          useradd -m builder
          echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          chown -R builder:builder .
          sudo -u builder makepkg -f --noconfirm

      - name: Set up repository
        run: |
          mkdir -p repo/x86_64
          mv *.pkg.tar.zst repo/x86_64/
          cd repo/x86_64
          repo-add ls3.db.tar.gz *.pkg.tar.zst

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
          publish_branch: gh-pages
          force_orphan: true
