name: Publish to personal AUR
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git base-devel sudo go fakeroot namcap`

      - name: Create build user
        run: |
          useradd -m -G wheel builder
          echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          chown -R builder:builder .

      - name: Validate PKGBUILD
        run: |
          if ! sudo -u builder bash -c 'cd $GITHUB_WORKSPACE && namcap PKGBUILD'; then
            echo "PKGBUILD validation failed"
            exit 1
          fi

      - name: Build package
        run: |
          if ! sudo -u builder bash -c 'cd $GITHUB_WORKSPACE && makepkg -f --noconfirm --syncdeps'; then
            echo "Package build failed"
            exit 1
          fi

      - name: Verify package
        run: |
          if ! ls -la *.pkg.tar.zst; then
            echo "No package files found"
            exit 1
          fi
          if ! sudo -u builder bash -c 'namcap *.pkg.tar.zst'; then
            echo "Package verification failed"
            exit 1
          fi

      - name: Set up repository
        run: |
          mkdir -p repo/x86_64
          mv *.pkg.tar.zst repo/x86_64/
          cd repo/x86_64
          repo-add ls3.db.tar.gz *.pkg.tar.zst

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
          publish_branch: gh-pages
          force_orphan: true
